// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsz9ZYNCYpzunbnGN0MaCfMXt7ysI6Hj0',
    appId: '1:992806217770:web:3ff2bed5aa78e57b347b53',
    messagingSenderId: '992806217770',
    projectId: 'new-project-1402e',
    authDomain: 'new-project-1402e.firebaseapp.com',
    storageBucket: 'new-project-1402e.firebasestorage.app',
    measurementId: 'G-2LB990LGTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1yOsvzpgG9gN1rLrzx1Tm0EDS57JTQOE',
    appId: '1:992806217770:android:33a51d0d2d891b06347b53',
    messagingSenderId: '992806217770',
    projectId: 'new-project-1402e',
    storageBucket: 'new-project-1402e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamgIAMKWWwxm5EBXoI9TDUoYNTlFh9GM',
    appId: '1:992806217770:ios:6fb8fab565871c21347b53',
    messagingSenderId: '992806217770',
    projectId: 'new-project-1402e',
    storageBucket: 'new-project-1402e.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamgIAMKWWwxm5EBXoI9TDUoYNTlFh9GM',
    appId: '1:992806217770:ios:6fb8fab565871c21347b53',
    messagingSenderId: '992806217770',
    projectId: 'new-project-1402e',
    storageBucket: 'new-project-1402e.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsz9ZYNCYpzunbnGN0MaCfMXt7ysI6Hj0',
    appId: '1:992806217770:web:ed8374172cd936b9347b53',
    messagingSenderId: '992806217770',
    projectId: 'new-project-1402e',
    authDomain: 'new-project-1402e.firebaseapp.com',
    storageBucket: 'new-project-1402e.firebasestorage.app',
    measurementId: 'G-DDQ90LS30G',
  );
}
